### ISSUE TITLE
API para precio de envío

### ISSUE THREAD

**Issue by sergiomalv** [Arquisoft/dede_es4a#110]
Se debe buscar una API para poder calcular los costes de envío de un producto.

**Comment by sergiomalv** [comment]
@uo277931 y yo hemos decidido que los envíos contendrán unas medidas estándar para todos. Se comentará al resto del equipo en la próxima reunión.

**Comment by sergiomalv** [comment]
Se va a intentar utilizar una API de DHL. Estamos a la espera de que nos acepten la petición para usar su API.

**Comment by sergiomalv** [comment]
El API key de DHL no ha sido concedida, estamos buscando un nuevo servicio.

**Comment by uo277931** [comment]
Tras buscar varias API y encontrar problemas para que nos concedan las API key, finalmente hemos encotrado Shippo, la cual nos permite calcular tiempo estimado de llegada y costes de envío.

**Comment by uo277931** [comment]
Utilizaremos finalmente la API Shippo ya que nos ha funcionado correctamente.
